export const types = {
    FETCH_ALL: `FETCH_ALL`,
    ADD_ITEM_TO_BASKET: `ADD_ITEM_TO_BASKET`,
    REMOVE_ITEM_FROM_BASKET: `REMOVE_ITEM_FROM_BASKET`,
    CALCULATE_TOTAL_PRICE:`CALCULATE_TOTAL_PRICE`,
CHANGE_DELIVERY: 'CHANGE_DELIVERY'
};

export default types;
