export const types = {
    FETCH_ITEMS: `FETCH_ITEMS`,
    FETCH_CATEGORIES: `FETCH_CATEGORIES`,
    ADD_ITEM_TO_BASKET: `ADD_ITEM_TO_BASKET`,
    REMOVE_ITEM_FROM_BASKET: `REMOVE_ITEM_FROM_BASKET`,
CHANGE_DELIVERY: 'CHANGE_DELIVERY',
    EMPTY_BASKET: `EMPTY_BASKET`,
    SEND_TO_BACK: `SEND_TO_BACK`
};

export default types;
